import MainHeader from "@/components/shared/header/MainHeader";
import HeaderWithNameAndProfile from "../../../components/pages/gptVetting/HeaderWithNameAndProfile/HeaderWithNameAndProfile";

/* 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */
export default function GptVettingInterview({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderWithNameAndProfile />
      {children}
      <p className="text-center my-2">
        Powered by{" "}
        <span className="link link-primary no-underline">Recruit</span>
      </p>
    </>
  );
}
